### ISSUE TITLE
Slow capture when using Auto Capture

### ISSUE THREAD

**Issue by tahnik** [jangxx/node-win-desktop-duplication#3] opened 2020-12-06 20:52 UTC
When using a delay of 0, it's capturing 64 frames in 2 seconds. Isn't Desktop Duplication API supposed to be super fast? Is there a reason why it isn't capturing 60 frames a second?

**Comment by tahnik** [comment] 2020-12-06 21:05
Also, this is the PNG I am getting when I trying the capture thread example. Any idea why this might happen?

![test_frame_0](https://user-images.githubusercontent.com/9964210/101292315-b5716980-3806-11eb-8ca9-a615a44c7230.png)

**Comment by jangxx** [comment] 2020-12-07 10:49
>When using a delay of 0, it's capturing 64 frames in 2 seconds. Isn't Desktop Duplication API supposed to be super fast? Is there a reason why it isn't capturing 60 frames a second?

There are multiple reasons for this. First, the DesktopDuplication API only supplies new frames if the screen content has changed. If you're looking at a static picture you may never even get a single frame unless the content is updated somehow. If you're watching a 30fps video, you are only ever going to get 30 frames a second and not 60. Second (and I've already mentioned this here: https://github.com/jangxx/node-win-desktop-duplication/issues/2), the code is really not at all optimized for video capture or for capturing images quickly. I'm still standing by my statement, that this would be very hard to do with Node anyway and you'd be better off using C++ if you want to do video recording.

>Also, this is the PNG I am getting when I trying the capture thread example. Any idea why this might happen?

The image looks like the library has somehow messed up the screen dimensions. Does the size of the image match your actual screen resolution (3440x1440)? I need some more information about your setup, otherwise I can't reproduce your issue unfortunately.

**Comment by tahnik** [comment] 2020-12-07 19:39
Hey @jangxx, thanks for your reply.

So the dimensions seems fine. My monitor has a resolution of 3440x1440, the PNG files have the same resolution.

As for your comment on the FPS, I did try playing a 60FPS video and a game, it still seems to always capture around 30ish frames every second.

I will try to run your code in a pure C++ environment and see what the result is. I found some other examples of Desktop Duplication API but yours seems to be the most clean and well organised. If I don't manage to figure it our within a week I will close this issue.

**Comment by jangxx** [comment] 2020-12-08 10:07
>I will try to run your code in a pure C++ environment and see what the result is.

Feel free to try it out, without the last step of copying the image contents into a Node buffer, you will probably see a slight performance improvement. Don't orient yourself after my code too much though. Like I said, it's really inefficient and not optimized for high framerate capturing. If you look into the `getFrame` method for example, you can see, that I am

1. Creating a new "staging" texture
2. Copying the captured frame into that texture
3. Copying the staging texture into another texture
4. Calling `getImageData`, which copies the contents of that texture pixel-by-pixel into a buffer

Afterwards I'm cloning that last buffer _again_ in the wrapper code and then I pass it synchronously back to Node. Not only is all of that cloning and copying inefficient, it's also all happening in the same thread, so it's no wonder you are not getting high framerates. In a pure C++ implementation, you would remove all unnecessary operations and also run the code that's not directly involved in the capturing process in another thread for vastly better performance.

Anyway, good luck with your implementation, I'm sure you can build a far more efficient image capture program if you're actually optimizing it for high framerates instead of just trying to somehow get a captured image into Node, like I did.

**Comment by felladrin** [comment] 2021-01-12 22:06
Hi there, I'd like to add some data to this issue:
I'm having the same issue @tahnik mentioned, about the image:
![image](https://user-images.githubusercontent.com/418083/104378630-f90b7180-5530-11eb-96b5-bbffaf552adc.png)

But I noticed it was happening only when using specific resolutions. So I mapped some resolutions with their results, and actually there were only a two (among some popular resolutions) that were having this error:


<table>
<tr>
	<td>Resolution
	<td>Result
<tr>
	<td>2560 x 1600
	<td>✓ Works Fine
<tr>
	<td>2560 x 1440
	<td>✓ Works Fine
<tr>
	<td>1920 x 1080
	<td>✓ Works Fine
<tr>
	<td>1680 x 1050
	<td>✗ Has the issue
<tr>
	<td>1280 x 1024
	<td>✓ Works Fine
<tr>
	<td>1366 x 768
	<td>✗ Has the issue
<tr>
	<td>1280 x 800
	<td>✓ Works Fine
<tr>
	<td>1280 x 720
	<td>✓ Works Fine
<tr>
	<td>1024 x 768
	<td>✓ Works Fine
</table>

All resolutions were tested in a Windows with Display Scaling 100%.

Considering `1366 x 768` and `1024 x 768` have the same height, makes me think the issue is related to the width.

**Comment by jangxx** [comment] 2021-01-13 08:45
Huh, that's very weird. Thanks for mapping out some resolutions, though. Now that I know which resolutions to test when debugging, I might actually find the error. I will take a look sometime in the coming days when I get around to it.

**Comment by felladrin** [comment] 2021-01-13 23:44
Out of curiosity, the resolution widths that are causing error (3440, 1680, 1366) are numbers not divisible by 32 (the number of bits for RGBA pixel definition).

**Comment by jangxx** [comment] 2021-01-14 09:25
Okay, I have tried to reproduce the issue with your resolutions, but unfortunately I wasn't able to. I set my Windows VM to a multitude of different resolutions, and I got the correct frame for every one of them.

To further narrow down the issue, I have added some debug logging to a few functions however, which can be enabled by commenting in line 13 of _/src/desktopduplication.h_. If you have the time, please do the following and then report back the log outputs:

1. Comment in line 13 of _/src/desktopduplication.h_
2. Run `node-gyp build`
3. Run `node examples/get_frame.js`

I have the feeling, that the library is _somehow_ getting the wrong screen dimensions from Windows itself, but since I can't reproduce the issue myself, it would be really helpful if you could check that for me.

**Comment by felladrin** [comment] 2021-01-14 14:19
That's true. I ran the example (https://github.com/jangxx/node-win-desktop-duplication/blob/master/examples/get_frame.js) in a _Windows 10 inside VirtualBox_ and had no problem with the screenshots. And it was outputting the correct size:

```
Got frame!
Width: 1366 Height: 768
```

Right after that, I tried it on a _Windows Server 2019 with nVidia_, with the same resolution, and it returned the image with the issue.

![image](https://user-images.githubusercontent.com/418083/104611636-05591100-568e-11eb-8a28-fcc4321c7288.png)

But I've tried taking a screenshot with [Captura](https://github.com/MathewSachin/Captura) (that also uses Desktop Duplication API) and it took the screenshot correctly on Windows Server:

![image](https://user-images.githubusercontent.com/418083/104607777-d771cd80-5689-11eb-9774-6eeec43667ba.png)

**Comment by jangxx** [comment] 2021-01-15 00:49
Okay, I think I have finally fixed it. I was actually able to reproduce the problem on my second and third monitor and then looked for the solution for like 2 hours. In the end it seems like the mapped texture data has some black pixels on the right to get to a number divisible by 32 or something, but only when it isn't the only monitor? I don't know, to me this makes absolutely no sense, but I guess that's Windows for you. I have committed and pushed a new version; please try if it also fixes the bug on your PC, in which case I would publish it to npm, together with the contents of your PRs.

**Comment by felladrin** [comment] 2021-01-15 09:23
That's awesome! Just tested it and now it's working perfectly for all resolutions!

![image](https://user-images.githubusercontent.com/418083/104705112-2bc88c00-5722-11eb-9a4e-d076db5dda0d.png)

![image](https://user-images.githubusercontent.com/418083/104705591-c45f0c00-5722-11eb-8962-21900009baed.png)

I was not able to test 3440x1440 for @tahnik, but I guess it's also working fine now.

Thank you!

**Comment by jangxx** [comment] 2021-01-15 09:28
That's great to hear! I have just published version 1.0.2 to npm and with that, I think we can close this issue now.

**Closed as completed by jangxx** 2021-01-15 09:28 UTC
